### ISSUE TITLE
After including this addon receiving error while running storybook

### ISSUE THREAD

**Issue by suyesh** [aholachek/storybook-mobile#1]
`Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules`

**Comment by aholachek** [comment]
Hi, thanks for making this issue. It seems like this is[ some kind of CORS issue](https://stackoverflow.com/questions/48753691/cannot-access-cssrules-from-local-css-file-in-chrome-64/49160760#49160760), but I can't reproduce. Can you give me any more details about your browser or development setup? Or maybe a screenshot of the entire error if there's any more information like a stacktrace?

**Comment by suyesh** [comment]
@aholachek 
![Screen Shot 2020-04-29 at 5 32 21 PM](https://user-images.githubusercontent.com/3803603/80649131-72b10d00-8a3f-11ea-8508-872b38e29057.png)

**Comment by aholachek** [comment]
It seems to be [related to accessing css from the local filesystem](https://stackoverflow.com/questions/48753691/cannot-access-cssrules-from-local-css-file-in-chrome-64/49160760#49160760) which should not be what is happening when storybook is running. Since I can't reproduce this on chrome (current or canary), Firefox, or Safari, I will just leave this issue open in case someone else encounters the same thing.

**Comment by lada** [comment]
Same problem
<img width="897" alt="Screenshot 2020-05-25 at 15 07 41" src="https://user-images.githubusercontent.com/179279/82815448-85313180-9e99-11ea-9a8f-0e3de5f7b5e2.png">

**Comment by aholachek** [comment]
Hi @lada @suyesh, would either of you be willing to try the most recent release (https://github.com/aholachek/storybook-mobile/releases/tag/v0.1.22)? I cannot reproduce this locally but I saw [a similar issue here](https://github.com/odoo/odoo/issues/22517) and copied how they handled it

**Comment by lada** [comment]
Hi @aholachek , for me the last release works fine! Thanks for fixing it and especially thank you for this great addon!

**Comment by aholachek** [comment]
Thank you for checking so quickly @lada! I'll close this issue for now, but if anyone sees anything similar please feel free to reopen.

**Comment by lada** [comment]
Hi @aholachek, it seems that the problem has been reintroduced in the last release

**Comment by aholachek** [comment]
@lada thanks so much for reporting this (and bearing with me). Would you mind trying version 0.1.24 that I just released? My new hypothesis is that the errors are caused by stylesheets coming from chrome extensions, which means I can just [catch the errors and ignore them](https://github.com/aholachek/storybook-mobile/blob/master/src/utils.js#L6).

**Comment by lada** [comment]
@aholachek I will try the new version and will let you know.
But I'm afraid the problem is not caused by Chrome extensions. I'm getting the same error also in Guest mode without any extensions active. It is present even in Firefox - see here:
<img width="831" alt="Screenshot 2020-06-01 at 15 27 13" src="https://user-images.githubusercontent.com/179279/83413856-d0f55500-a41c-11ea-9f26-920db543ee0f.png">

**Comment by lada** [comment]
@aholachek OK, so I've just tried the latest release and it works fine! Thank you!

**Comment by suyesh** [comment]
The new version fixes the issue. 

> Hi @lada @suyesh, would either of you be willing to try the most recent release (https://github.com/aholachek/storybook-mobile/releases/tag/v0.1.22)? I cannot reproduce this locally but I saw [a similar issue here](https://github.com/odoo/odoo/issues/22517) and copied how they handled it
